"""Add author

Revision ID: 7d519cc47dd4
Revises: 2430db7b86b9
Create Date: 2019-08-07 19:44:57.555325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d519cc47dd4'
down_revision = '2430db7b86b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('author', sa.String(length=64), nullable=True))
    op.create_foreign_key(None, 'post', 'user', ['author'], ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'author')
    # ### end Alembic commands ###
